from __future__ import annotations

import re
from datetime import datetime, timezone

import httpx
from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse

from app.services.config_store import config_store
from app.services.store import store

router = APIRouter(prefix="/api/hackathon", tags=["hackathon"])


def _analysis_report_md(a) -> str:
    evidence = "\n".join(
        f"- **{e.id}** — {e.title}: {e.detail} ({e.source}{f', {e.location}' if e.location else ''})"
        for e in a.evidence
    ) or "- No verified blocking evidence."
    claims = "\n".join(
        f"- `{c.status.upper()}` {c.text}" + (f" — {c.reason}" if c.reason else "")
        for c in a.claims
    ) or "- No claims were generated."
    trajectory = "\n".join(
        f"{t.order}. **{t.agent}** — {t.summary} (`{t.status}`)"
        for t in a.trajectory
    ) or "No trajectory recorded."
    return f"""# ChangeGuard Review — PR #{a.pull_request}

**Repository:** {a.repo}  
**Decision:** {a.decision.value.upper()}  
**Severity:** {a.severity.value.upper()}  
**Confidence:** {round(a.confidence * 100)}%  
**Run:** {a.id}

## Predicted failure

{a.predicted_failure}

{a.failure_detail}

## Recommendation

{a.recommendation}

## Verified evidence

{evidence}

## Claims

{claims}

## Agent trajectory

{trajectory}

---
Generated by ChangeGuard. AI-proposed risks are only promoted when the verifier can link them to evidence.
"""


def _benchmark_report_md(b: dict) -> str:
    metrics = "\n".join(
        f"| {m['name']} | {m['baseline']}{m['unit']} | {m['changeguard']}{m['unit']} | {m['changeguard']-m['baseline']:+}{m['unit']} |"
        for m in b.get("metrics", [])
    )
    rows = "\n".join(
        f"| {r.get('case')} | {r.get('truth')} | {r.get('baseline')} | {r.get('changeguard')} | {'yes' if r.get('challenge') else 'no'} |"
        for r in b.get("results", [])
    )
    verification = b.get("verification") or {}
    tokens = b.get("token_usage") or {}
    return f"""# ChangeGuard Benchmark Report

**Created:** {b.get('created_at','—')}  
**Type:** {b.get('benchmark_type','—')}  
**Cases:** {b.get('cases',0)} ({b.get('challenging_cases',0)} challenging)  
**Baseline score:** {b.get('baseline_score','—')}%  
**ChangeGuard score:** {b.get('overall_score','—')}%  
**Measured improvement:** {b.get('improvement',0):+} percentage points

## Metrics

| Metric | Baseline | ChangeGuard | Delta |
|---|---:|---:|---:|
{metrics}

## Verification

- Supported AI claims: {verification.get('supported_ai_claims','N/A')}
- Rejected AI claims: {verification.get('rejected_ai_claims','N/A')}
- Baseline tokens: {tokens.get('baseline','N/A')}
- ChangeGuard tokens: {tokens.get('changeguard','N/A')}

## Cases

| Case | Truth | Baseline | ChangeGuard | Challenging |
|---|---|---|---|---|
{rows}

## Protocol

The official agentic benchmark uses the same configured LLM for both systems. The baseline receives the change in a single prompt. ChangeGuard adds deterministic rules, structured risk generation, and exact evidence verification before producing a decision.
"""


@router.get("/analyses/{analysis_id}/trajectory.json")
async def export_trajectory(analysis_id: str):
    a = store.get(analysis_id)
    if not a:
        raise HTTPException(404, detail="Analysis not found")
    return {
        "analysis_id": a.id,
        "repository": a.repo,
        "pull_request": a.pull_request,
        "decision": a.decision.value,
        "created_at": a.created_at.isoformat(),
        "run_details": a.run_details.model_dump() if a.run_details else None,
        "trajectory": [t.model_dump() for t in a.trajectory],
        "claims": [c.model_dump() for c in a.claims],
        "evidence": [e.model_dump() for e in a.evidence],
    }


@router.get("/analyses/{analysis_id}/report.md", response_class=PlainTextResponse)
async def export_analysis_report(analysis_id: str):
    a = store.get(analysis_id)
    if not a:
        raise HTTPException(404, detail="Analysis not found")
    return PlainTextResponse(
        _analysis_report_md(a),
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="changeguard-{analysis_id}.md"'},
    )


@router.get("/benchmarks/latest.md", response_class=PlainTextResponse)
async def export_benchmark_report():
    b = config_store.latest_benchmark()
    if not b:
        raise HTTPException(404, detail="No benchmark has been run yet")
    return PlainTextResponse(
        _benchmark_report_md(b),
        media_type="text/markdown",
        headers={"Content-Disposition": 'attachment; filename="changeguard-benchmark.md"'},
    )


@router.post("/github-review/{analysis_id}")
async def create_github_review(analysis_id: str):
    a = store.get(analysis_id)
    if not a:
        raise HTTPException(404, detail="Analysis not found")
    cfg = config_store.get_all()
    token = cfg.get("github_token")
    if not token:
        raise HTTPException(400, detail="Configure a GitHub token before writing review comments")
    if not a.source_url:
        raise HTTPException(400, detail="This analysis is not linked to a GitHub pull request")
    match = re.match(r"https://github\.com/([^/]+)/([^/]+)/pull/(\d+)", a.source_url)
    if not match:
        raise HTTPException(400, detail="Unsupported GitHub pull request URL")
    owner, repo, pr = match.groups()
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "User-Agent": "ChangeGuard/0.6",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr}/comments"
    async with httpx.AsyncClient(timeout=20, headers=headers) as client:
        response = await client.post(url, json={"body": _analysis_report_md(a)})
    if response.status_code >= 400:
        detail = f"GitHub returned HTTP {response.status_code}"
        if response.headers.get("content-type", "").startswith("application/json"):
            detail = response.json().get("message", detail)
        raise HTTPException(response.status_code, detail=detail)
    data = response.json()
    return {"ok": True, "url": data.get("html_url"), "comment_id": data.get("id")}


@router.get("/submission-status")
async def submission_status():
    latest = config_store.latest_benchmark()
    analyses = store.list_full(limit=100)
    has_agentic = bool(latest and latest.get("benchmark_type") == "single-prompt-vs-agentic")
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "checks": [
            {"name": "Real GitHub PR analysis", "ready": bool(analyses)},
            {"name": "Representative trajectories", "ready": any(a.trajectory for a in analyses)},
            {"name": "15-case benchmark dataset", "ready": True},
            {"name": "Same-model single-prompt baseline", "ready": True},
            {"name": "Official agentic benchmark executed", "ready": has_agentic},
            {"name": "Reproduction guide", "ready": True},
            {"name": "Improvement changelog", "ready": True},
            {"name": "5-minute demo script", "ready": True},
        ],
    }
